#!/bin/bash
set -x

jdep_install_path=/etc/jdep
jdep_alias=/usr/bin/jdep
jdep_cmd=$(readlink -e $0)


function jdep_exit {

	exit_reason=$1
	cat ${jdep_install_path}/.internals/jdep/jdep_msg.json | jq -r ".jdep_exit_msg.${exit_reason}[]"
	set +x
	exit 1
}


if [ "${jdep_cmd}" == "$(readlink -e ${jdep_alias})" ]
then
	echo "Called from alias."
else
	source ./.internals/jdep/do_install_jdep.sh
fi

if [ -f "${jdep_file}" ]
then
        source ${jdep_install_path}/do_deploy.sh
else
	jdep_exit "nothing_to_deploy"
fi

set +x


