#!/bin/bash
set -x

jdep_install_path=/etc/jdep
jdep_alias=/usr/bin/jdep
jdep_cmd=$(readlink -e $0)


if [ "${jdep_cmd}" == "${jdep_alias}" ]
then
	echo "Called from alias."
else
	source ./.internals/jdep/do_install_jdep.sh
fi

if [ -f "${jdep_file}" ]
then
        source ${jdep_install_path}/do_deploy.sh
else
        echo "${jdep_file} - Nothing to deploy. Aborting."
fi

set +x


